apiVersion: v1
kind: Service
metadata:
  name: gpu-3pod-service
  namespace: hls
spec:
  selector:
    app: gpu-3pod
  ports:
    - name: gpu-3pod-1-port
      protocol: TCP
      port: 3002
      targetPort: 3002
    - name: gpu-3pod-2-port
      protocol: TCP
      port: 3003
      targetPort: 3003
    - name: gpu-3pod-3-port
      protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP